"""empty message

Revision ID: 47ca2611971d
Revises: 03eb4276f019
Create Date: 2022-07-09 17:36:13.507327

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '47ca2611971d'
down_revision = '03eb4276f019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'internal_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('product', 'price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('product', 'internal_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
