"""empty message

Revision ID: 9ee01c75b939
Revises: e6f0072db682
Create Date: 2022-07-08 03:05:19.534418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ee01c75b939'
down_revision = 'e6f0072db682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('product', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'updated_at')
    op.drop_column('product', 'created_at')
    # ### end Alembic commands ###
